<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7FzaqEH\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7FzaqEH/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container7FzaqEH.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container7FzaqEH\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container7FzaqEH\appAppKernelProdContainer([
    'container.build_hash' => '7FzaqEH',
    'container.build_id' => '56f48343',
    'container.build_time' => 1685708605,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7FzaqEH');
