<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9Mxfcox\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9Mxfcox/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container9Mxfcox.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container9Mxfcox\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container9Mxfcox\appAppKernelProdContainer([
    'container.build_hash' => '9Mxfcox',
    'container.build_id' => '31b319fe',
    'container.build_time' => 1685708343,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9Mxfcox');
